#lang racket/base
(require rackunit "../runner/static/types.rkt" "../runner/static/type-display.rkt")
(define a (type-variable 73))
(define b (type-variable 12))
(define c (type-variable 99))
(test-case "arrow grouping and quantifiers have deterministic source-independent names"
  (check-equal? (type->string (arrow-type a (arrow-type b c))) "a -> b -> c")
  (check-equal? (type->string (arrow-type (arrow-type a b) (arrow-type a b))) "(a -> b) -> a -> b")
  (check-equal? (scheme->string (scheme '(73 12) (arrow-type (arrow-type a b) (arrow-type a b)) '()))
                "forall a b. (a -> b) -> a -> b")
  (check-equal? (scheme->string (scheme '(73) (arrow-type a a) '())) "forall a. a -> a")
  (check-equal? (scheme->string (scheme '(73) (arrow-type a (list-type a)) '(73)))
                "forall a:data. a -> List(a)")
  (check-equal? (type->string (base-type 'Error)) "Error")
  (check-equal? (type->string (map-type a (result-type (option-type (base-type 'String)))))
                "Map(a, Result(Option(String)))")
  (check-equal? (scheme->string (scheme '() (arrow-type (base-type 'Rat) (base-type 'Rat)) '()))
                "Rat -> Rat")
  (check-equal? (scheme->string (scheme '(73) (base-type 'Unit) '())) "forall a. Unit"))
(test-case "large quantified schemes retain unique stable display names"
  (define ids (build-list 28 values))
  (define value (scheme ids (type-variable 27) '(26)))
  (check-equal? (scheme->string value)
                "forall a b c d e f g h i j k l m n o p q r s t u v w x y z a1:data b1. b1"))
