#lang racket/base

;; One private audited inventory. Partial schemes contain
;; audited input obligations and an explanatory success hint ONLY. Their arity
;; is the number of inputs before the unrepresented result; inference must never
;; publish the hint as a verified output. Pending entries are internal failures.
(require racket/list "types.rkt")
(provide (struct-out library-contract) catalog contract-ref validate-catalog)
(struct library-contract (id status signature arity gap-code reason implementations tests) #:transparent)
(define rat (base-type 'Rat))
(define bool (base-type 'Bool))
(define string (base-type 'String))
(define char (base-type 'Char))
(define byte (base-type 'Byte))
(define unit (base-type 'Unit))
(define error-type (base-type 'Error))
(define a (type-variable 0))
(define b (type-variable 1))
(define (entry id parameters result implementations tests
               [variables '()] [restricted '()] [gap-code #f] [reason #f])
  (library-contract (if (string? id) (string->symbol id) id) (if gap-code 'partial 'complete)
                    (scheme variables (foldr arrow-type result parameters) restricted)
                    (length parameters) gap-code reason implementations tests))

(define catalog
  (append
   (for/list ([row '((succ typed-rat-succ) (add typed-rat-add) (sub typed-rat-sub)
                    (mult typed-rat-mult) (eq typed-rat-equal) (lt typed-rat-less)
                    (lte typed-rat-less-equal) (gt typed-rat-greater) (gte typed-rat-greater-equal)
                    (is-zero typed-rat-is-zero) (neg typed-rat-negate)
                    (abs typed-rat-abs) (floor typed-rat-floor) (exp typed-rat-exp)
                    (recip typed-rat-recip) (is-whole typed-rat-is-whole)
                    (is-nonnegative-whole typed-rat-is-nonnegative-whole))])
     (define id (car row))
     (entry id (if (memq id '(succ is-zero neg abs floor recip is-whole is-nonnegative-whole))
                   (list rat) (list rat rat))
            (cond [(memq id '(eq lt lte gt gte is-zero is-whole is-nonnegative-whole)) bool]
                  [(memq id '(exp recip)) (result-type rat)] [else rat])
            (list (list "core/typed-rat.rkt" (cadr row)) (list "core/rat.rkt" 'raw-make-rat))
            '("tests/typed-rat-test.rkt" "tests/rat-test.rkt")))
   (for/list ([row '((TRUE TRUE) (FALSE FALSE) (not typed-not) (and typed-and)
                    (or typed-or) (xor typed-xor))])
     (define id (car row))
     (entry id (cond [(memq id '(TRUE FALSE)) '()] [(eq? id 'not) (list bool)] [else (list bool bool)]) bool
            (list (list "core/typed-logic.rkt" (cadr row))) '("tests/typed-logic-test.rkt")))
   (list
    (entry 'if (list bool a a) a '(("core/typed-logic.rkt" typed-if))
           '("tests/typed-logic-test.rkt" "tests/language-test.rkt") '(0))
    (entry 'div (list rat rat) (result-type rat)
           '(("core/typed-rat.rkt" typed-rat-div) ("core/rat.rkt" raw-rat-div))
           '("tests/typed-rat-test.rkt" "tests/result-test.rkt"))
    (entry 'is-ok (list (result-type a)) bool '(("core/result.rkt" typed-result-is-ok))
           '("tests/result-test.rkt") '(0) '(0))
    (entry 'unwrap-ok (list (result-type a)) a
           '(("core/result.rkt" typed-result-unwrap-ok) ("core/result.rkt" raw-result-unwrap-ok))
           '("tests/result-test.rkt") '(0) '(0) 'UNREPRESENTED_ERROR_ALTERNATIVE
           "WrongResultVariant may return Error; V1 does not refine Result variants.")
    (entry 'error-to-string (list error-type) string '(("core/to-string.rkt" typed-error-to-string))
           '("tests/to-string-test.rkt" "tests/render-error-test.rkt")))
   (for/list ([row '(("char-eq" typed-char-equal) ("char-lt" typed-char-less)
                    ("char-lte" typed-char-less-equal) ("char-gt" typed-char-greater)
                    ("char-gte" typed-char-greater-equal))])
     (entry (car row) (list char char) bool (list (list "core/chars.rkt" (cadr row)))
            '("tests/chars-test.rkt")))
   (for/list ([row '(("byte-eq" typed-byte-equal) ("byte-lt" typed-byte-less)
                    ("byte-lte" typed-byte-less-equal) ("byte-gt" typed-byte-greater)
                    ("byte-gte" typed-byte-greater-equal))])
     (entry (car row) (list byte byte) bool (list (list "core/byte.rkt" (cadr row)))
            '("tests/byte-test.rkt")))
   (list
    (entry "UNIT" '() unit '(("core/unit.rkt" UNIT)) '("tests/unit-test.rkt"))
    (entry "EMPTY-STRING" '() string '(("core/strings.rkt" EMPTY-STRING)) '("tests/strings-test.rkt"))
    (entry "make-char" (list rat) char '(("core/chars.rkt" typed-make-char-rat)
                                         ("core/chars.rkt" raw-make-checked-char-rat))
           '("tests/chars-test.rkt") '() '() 'UNREPRESENTED_ERROR_ALTERNATIVE
           "Rat must be an integer from 0 through 255; InvalidCount or InvalidChar may return Error.")
    (entry "make-byte" (list rat) byte '(("core/byte.rkt" typed-make-byte)
                                         ("core/byte.rkt" raw-make-checked-byte))
           '("tests/byte-test.rkt") '() '() 'UNREPRESENTED_ERROR_ALTERNATIVE
           "Rat must be an integer from 0 through 255; InvalidByte may return Error.")
    (entry "byte-value" (list byte) rat '(("core/byte.rkt" typed-byte-value)) '("tests/byte-test.rkt"))
    (entry "string-to-bytes" (list string) (list-type byte)
           '(("core/byte.rkt" typed-string-to-bytes)) '("tests/byte-test.rkt"))
    (entry "bytes-to-string" (list (list-type byte)) string
           '(("core/byte.rkt" typed-bytes-to-string)) '("tests/byte-test.rkt"))
    (entry "make-string" (list (list-type char)) string
           '(("core/strings.rkt" typed-make-string)) '("tests/strings-test.rkt"))
    (entry "string-empty?" (list string) bool
           '(("core/strings.rkt" typed-string-empty?)) '("tests/strings-test.rkt"))
    (entry "string-length" (list string) rat
           '(("core/strings.rkt" typed-string-length-rat)) '("tests/strings-test.rkt"))
    (entry "string-append" (list string string) string
           '(("core/strings.rkt" typed-string-append)) '("tests/strings-test.rkt"))
    (entry "string-head" (list string) char '(("core/strings.rkt" typed-string-head))
           '("tests/strings-test.rkt") '() '() 'UNREPRESENTED_ERROR_ALTERNATIVE
           "An empty String returns Error; V1 has no nonempty refinement.")
    (entry "string-tail" (list string) string '(("core/strings.rkt" typed-string-tail))
           '("tests/strings-test.rkt") '() '() 'UNREPRESENTED_ERROR_ALTERNATIVE
           "An empty String returns Error; V1 has no nonempty refinement."))
   (for/list ([row '(("string-eq" typed-string-equal) ("string-prefix?" typed-string-prefix?)
                    ("string-contains?" typed-string-contains?))])
     (entry (car row) (list string string) bool (list (list "core/strings.rkt" (cadr row)))
            '("tests/strings-test.rkt")))
   (list
    (entry "NIL" '() (list-type a) '(("core/errors.rkt" NIL)) '("tests/lists-test.rkt") '(0) '(0))
    (entry "cons" (list a (list-type a)) (list-type a) '(("core/lists.rkt" typed-cons))
           '("tests/lists-test.rkt") '(0) '(0))
    (entry "is-nil" (list (list-type a)) bool '(("core/lists.rkt" typed-is-nil))
           '("tests/lists-test.rkt") '(0) '(0))
    (entry "len" (list (list-type a)) rat '(("core/list-nat.rkt" typed-len-rat))
           '("tests/list-nat-test.rkt") '(0) '(0))
    (entry "append" (list (list-type a) (list-type a)) (list-type a)
           '(("core/list-transform.rkt" typed-append)) '("tests/list-transform-test.rkt") '(0) '(0))
    (entry "reverse" (list (list-type a)) (list-type a)
           '(("core/list-transform.rkt" typed-reverse)) '("tests/list-transform-test.rkt") '(0) '(0))
    (entry "concat" (list (list-type (list-type a))) (list-type a)
           '(("core/list-transform.rkt" typed-concat)) '("tests/list-transform-test.rkt") '(0) '(0))
    ;; Every pair is a two-element List, so its members share the same domain.
    (entry "zip" (list (list-type a) (list-type a)) (list-type (list-type a))
           '(("core/list-transform.rkt" typed-zip) ("core/list-transform.rkt" raw-zip-step))
           '("tests/list-transform-test.rkt") '(0) '(0))
    (entry "head" (list (list-type a)) a '(("core/lists.rkt" typed-head))
           '("tests/lists-test.rkt") '(0) '(0) 'UNREPRESENTED_ERROR_ALTERNATIVE
           "An empty List returns Error; V1 has no nonempty refinement.")
    (entry "tail" (list (list-type a)) (list-type a) '(("core/lists.rkt" typed-tail))
           '("tests/lists-test.rkt") '(0) '(0) 'UNREPRESENTED_ERROR_ALTERNATIVE
           "An empty List returns Error; V1 has no nonempty refinement."))
   (list
    (entry "map" (list (arrow-type a b) (list-type a)) (list-type b)
           '(("core/list-transform.rkt" typed-map)) '("tests/list-transform-test.rkt") '(0 1) '(0 1))
    (entry "filter" (list (arrow-type a bool) (list-type a)) (list-type a)
           '(("core/list-transform.rkt" typed-filter)) '("tests/list-transform-test.rkt") '(0) '(0))
    (entry "reduce" (list (arrow-type b (arrow-type a b)) b (list-type a)) b
           '(("core/list-transform.rkt" typed-reduce)) '("tests/list-transform-test.rkt") '(0 1) '(0 1))
    (entry "contains?" (list (arrow-type a (arrow-type a bool)) a (list-type a)) bool
           '(("core/list-search.rkt" typed-contains?)) '("tests/list-search-test.rkt") '(0) '(0))
    (entry "make-map" (list (arrow-type a (arrow-type a bool))) (map-type a b)
           '(("core/map.rkt" typed-make-map) ("core/map.rkt" raw-comparison-boolean))
           '("tests/map-test.rkt") '(0 1) '(0 1))
    (entry "map-empty?" (list (map-type a b)) bool
           '(("core/map.rkt" typed-map-empty?)) '("tests/map-test.rkt") '(0 1) '(0 1))
    (entry "map-size" (list (map-type a b)) rat
           '(("core/map.rkt" typed-map-size)) '("tests/map-test.rkt") '(0 1) '(0 1))
    (entry "map-lookup" (list (map-type a b) a) (option-type b)
           '(("core/map.rkt" typed-map-lookup)) '("tests/map-test.rkt") '(0 1) '(0 1))
    (entry "map-contains?" (list (map-type a b) a) bool
           '(("core/map.rkt" typed-map-contains?)) '("tests/map-test.rkt") '(0 1) '(0 1))
    (entry "map-set" (list (map-type a b) a b) (map-type a b)
           '(("core/map.rkt" typed-map-set)) '("tests/map-test.rkt") '(0 1) '(0 1))
    (entry "map-remove" (list (map-type a b) a) (map-type a b)
           '(("core/map.rkt" typed-map-remove)) '("tests/map-test.rkt") '(0 1) '(0 1)))
   (for/list ([row (list (list "any?" 'typed-any? bool) (list "all?" 'typed-all? bool)
                        (list "find" 'typed-find (option-type a))
                        (list "find-index" 'typed-find-index (option-type rat))
                        (list "take-while" 'typed-take-while (list-type a))
                        (list "drop-while" 'typed-drop-while (list-type a)))])
     (entry (car row) (list (arrow-type a bool) (list-type a)) (caddr row)
            (list (list "core/list-search.rkt" (cadr row))) '("tests/list-search-test.rkt") '(0) '(0)))
   (list
    (entry "NONE" '() (option-type a) '(("core/option.rkt" NONE))
           '("tests/option-test.rkt") '(0) '(0))
    (entry "some" (list a) (option-type a) '(("core/option.rkt" typed-make-some))
           '("tests/option-test.rkt") '(0) '(0))
    (entry "is-some" (list (option-type a)) bool '(("core/option.rkt" typed-option-is-some))
           '("tests/option-test.rkt") '(0) '(0))
    (entry "is-none" (list (option-type a)) bool '(("core/option.rkt" typed-option-is-none))
           '("tests/option-test.rkt") '(0) '(0))
    (entry "option-case" (list (option-type a) (arrow-type a b) b) b
           '(("core/option.rkt" typed-option-case)) '("tests/option-test.rkt") '(0 1) '(0))
    (entry "make-ok" (list a) (result-type a) '(("core/result.rkt" typed-make-ok))
           '("tests/result-test.rkt") '(0) '(0))
    (entry "make-err" (list error-type) (result-type a) '(("core/result.rkt" typed-make-err))
           '("tests/result-test.rkt") '(0) '(0))
    (entry "is-err" (list (result-type a)) bool '(("core/result.rkt" typed-result-is-err))
           '("tests/result-test.rkt") '(0) '(0))
    (entry "unwrap-err" (list (result-type a)) error-type
           '(("core/result.rkt" typed-result-unwrap-err) ("core/result.rkt" raw-result-unwrap-err))
           '("tests/result-test.rkt") '(0) '(0)))
   (for/list ([row (list (list "rat-to-string" 'typed-rat-to-string rat)
                        (list "bool-to-string" 'typed-bool-to-string bool)
                        (list "unit-to-string" 'typed-unit-to-string unit)
                        (list "char-to-string" 'typed-char-to-string char)
                        (list "byte-to-string" 'typed-byte-to-string byte)
                        (list "string-to-string" 'typed-string-to-string string))])
     (entry (car row) (list (caddr row)) string (list (list "core/to-string.rkt" (cadr row)))
            '("tests/to-string-test.rkt")))
   (for/list ([row (list (list "list-to-string" 'typed-list-to-string (list-type a))
                        (list "option-to-string" 'typed-option-to-string (option-type a))
                        (list "result-to-string" 'typed-result-to-string (result-type a)))])
     (entry (car row) (list (caddr row)) string
            (list (list "core/to-string.rkt" (cadr row)) (list "core/render-value.rkt" 'raw-value-to-chars))
            '("tests/to-string-test.rkt") '(0) '(0)))
   (list
    (entry "map-to-string" (list (map-type a b)) string
           '(("core/to-string.rkt" typed-map-to-string) ("core/render-value.rkt" raw-render-map))
           '("tests/to-string-test.rkt") '(0 1) '(0 1))
    (entry "value-to-string" (list a) string
           '(("core/to-string.rkt" value-to-string) ("core/render-value.rkt" raw-value-to-chars))
           '("tests/to-string-test.rkt") '(0) '(0))
    (entry "take" (list rat (list-type a)) (list-type a)
           '(("core/list-nat.rkt" typed-take-rat)) '("tests/list-nat-test.rkt") '(0) '(0)
           'UNREPRESENTED_ERROR_ALTERNATIVE "A negative or fractional count returns InvalidCount Error.")
    (entry "drop" (list rat (list-type a)) (list-type a)
           '(("core/list-nat.rkt" typed-drop-rat)) '("tests/list-nat-test.rkt") '(0) '(0)
           'UNREPRESENTED_ERROR_ALTERNATIVE "A negative or fractional count returns InvalidCount Error.")
    (entry "nth" (list rat (list-type a)) (option-type a)
           '(("core/list-nat.rkt" typed-nth-rat)) '("tests/list-nat-test.rkt") '(0) '(0)
           'UNREPRESENTED_ERROR_ALTERNATIVE "A negative or fractional index returns InvalidCount Error.")
    (entry "repeat" (list rat a) (list-type a)
           '(("core/list-nat.rkt" typed-repeat-rat)) '("tests/list-nat-test.rkt") '(0) '(0)
           'UNREPRESENTED_ERROR_ALTERNATIVE "A negative or fractional count returns InvalidCount Error.")
    (entry "range" (list rat rat) (list-type rat)
           '(("core/list-nat.rkt" typed-range-rat)) '("tests/list-nat-test.rkt") '() '()
           'UNREPRESENTED_ERROR_ALTERNATIVE "Fractional endpoints return InvalidCount Error.")
    (entry "flatten" (list (list-type a)) (list-type b)
           '(("core/list-transform.rkt" typed-flatten)) '("tests/list-transform-test.rkt") '(0 1) '(0 1)
           'UNSUPPORTED_CONTRACT
           "Recursive flattening changes arbitrary List nesting; V1 cannot express the input/output relationship."))
   (list
    (entry "stdout" (list string) (result-type unit)
           '(("lang/expander.rkt" "stdout") ("effects/stdout.rkt" "make-stdout")
             ("runtime/host.rkt" "perform-stdout") ("runtime/codec.rkt" "object-ok"))
           '("tests/stdout-test.rkt" "tests/host-test.rkt" "tests/codec-test.rkt"))
    (entry "read-line" (list unit) (result-type (option-type string))
           '(("lang/expander.rkt" "language-read-line") ("effects/stdin.rkt" "make-read-line")
             ("runtime/host.rkt" "perform-read-line") ("runtime/codec.rkt" "bytes->object-string")
             ("runtime/codec.rkt" "object-some"))
           '("tests/stdin-test.rkt" "tests/stdin-stream-test.rkt" "tests/codec-test.rkt"))
    (entry "read-file" (list string) (result-type (list-type byte))
           '(("lang/expander.rkt" "read-file") ("effects/files.rkt" "make-read-file")
             ("runtime/host.rkt" "perform-read-file") ("runtime/codec.rkt" "bytes->object-byte-list"))
           '("tests/files-test.rkt" "tests/file-host-test.rkt" "tests/codec-test.rkt"))
    (entry "write-file" (list string (list-type byte)) (result-type unit)
           '(("lang/expander.rkt" "write-file") ("effects/files.rkt" "make-write-file")
             ("runtime/host.rkt" "perform-write-file") ("runtime/codec.rkt" "object-byte-list->bytes")
             ("runtime/codec.rkt" "object-ok"))
           '("tests/files-test.rkt" "tests/file-host-test.rkt" "tests/codec-test.rkt"))
    (entry "print" (list a) (result-type unit)
           '(("lang/expander.rkt" "language-print") ("effects/print.rkt" "make-print")
             ("core/to-string.rkt" "value-to-string") ("effects/stdout.rkt" "make-stdout")
             ("runtime/host.rkt" "perform-stdout"))
           '("tests/print-test.rkt" "tests/to-string-test.rkt" "tests/host-test.rkt") '(0) '(0)))
   (list
    (entry "host" (list (list-type a)) b
           '(("runtime/host.rkt" "host") ("runtime/host.rkt" "dispatch-request")
             ("effects/protocol.rkt" "make-host-bridge"))
           '("tests/host-test.rkt" "tests/static-effects-test.rkt") '(0 1) '(0)
           'UNSUPPORTED_CONTRACT
           "Raw host uses an operation-dispatched request protocol; V1 establishes no result contract.")
    (entry "exit" (list rat) a
           '(("lang/expander.rkt" "language-exit") ("effects/exit.rkt" "make-exit")
             ("effects/exit.rkt" "raw-make-exit-request") ("runtime/host.rkt" "perform-exit"))
           '("tests/exit-test.rkt" "tests/host-test.rkt") '(0) '()
           'UNREPRESENTED_ERROR_ALTERNATIVE
           "Only status 0 or 1 is accepted; other Rat values return Error. Successful exit does not return.")
    (entry "parse-http-request" (list string) (result-type string)
           '(("effects/http.rkt" "parse-http-request") ("effects/http.rkt" "raw-parse-http-request"))
           '("tests/http-test.rkt"))
    (entry "render-http-response" (list rat string) (result-type string)
           '(("effects/http-response.rkt" "render-http-response")
             ("effects/http-response.rkt" "raw-unsupported-http-status-result"))
           '("tests/http-test.rkt"))
    (entry "make-http-path-handler" (list string rat string rat string string) (result-type string)
           '(("effects/http-server.rkt" "make-http-path-handler")
             ("effects/http-response.rkt" "render-http-response"))
           '("tests/http-server-test.rkt")))
   (for/list ([id '("HTTP-STATUS-OK" "HTTP-STATUS-BAD-REQUEST" "HTTP-STATUS-NOT-FOUND"
                   "HTTP-STATUS-INTERNAL-SERVER-ERROR")])
     (entry id '() rat (list (list "effects/http-response.rkt" id)) '("tests/http-test.rkt")))
   (for/list ([row (list (list "tcp-connect" (list string rat) (result-type rat))
                        (list "tcp-listen" (list string rat rat) (result-type rat))
                        (list "tcp-accept" (list rat) (result-type rat))
                        (list "tcp-read" (list rat rat) (result-type (list-type byte)))
                        (list "tcp-write" (list rat (list-type byte)) (result-type unit))
                        (list "tcp-close" (list rat) (result-type unit)))])
     (define id (car row))
     (entry id (cadr row) (caddr row)
            (list (list "lang/expander.rkt" id)
                  (list "effects/tcp.rkt" (string-append "make-" id))
                  (list "effects/tcp.rkt" (string-append "raw-make-" id "-request"))
                  (list "runtime/host.rkt" (string-append "perform-" id))
                  (list "runtime/codec.rkt" "object-rat->exact"))
            '("tests/tcp-test.rkt" "tests/tcp-host-test.rkt" "tests/codec-test.rkt") '() '()
            'UNREPRESENTED_ERROR_ALTERNATIVE
            "Numeric fields require nonnegative integers; the pure wrapper may return InvalidCount Error."))
   (for/list ([id '("make-http-serve-one" "make-http-server")])
     (entry id (list (arrow-type a b) (arrow-type string (result-type string)) rat rat) (result-type unit)
            (list (list "effects/http-server.rkt" id)
                  (list "effects/http-server.rkt" "raw-use-http-handler-result")
                  (list "effects/tcp.rkt" "raw-make-tcp-read-request"))
            '("tests/http-server-test.rkt") '(0 1) '() 'UNSUPPORTED_CONTRACT
            "The injected host protocol is outside V1; numeric listener/read limits can also return Error."))))

(define (contract-ref id)
  (define found (findf (lambda (entry) (eq? id (library-contract-id entry))) catalog))
  (unless found (error 'static-contracts "unregistered resolved builtin"))
  (when (eq? (library-contract-status found) 'pending)
    (error 'static-contracts "pending builtin audit"))
  found)

(define (validate-catalog entries)
  (unless (and (list? entries) (andmap library-contract? entries)
               (= (length entries) (length (remove-duplicates (map library-contract-id entries)))))
    (error 'static-contracts "invalid contract inventory"))
  (for ([entry (in-list entries)])
    (unless (and (symbol? (library-contract-id entry))
                 (memq (library-contract-status entry) '(complete partial))
                 (scheme? (library-contract-signature entry))
                 (exact-nonnegative-integer? (library-contract-arity entry))
                 (pair? (library-contract-implementations entry))
                 (pair? (library-contract-tests entry))
                 (if (eq? (library-contract-status entry) 'partial)
                     (and (memq (library-contract-gap-code entry)
                                '(UNREPRESENTED_ERROR_ALTERNATIVE UNSUPPORTED_CONTRACT))
                          (string? (library-contract-reason entry)))
                     (and (not (library-contract-gap-code entry)) (not (library-contract-reason entry)))))
      (error 'static-contracts "pending or malformed builtin contract")))
  entries)
