#lang racket/base
;; Exact private frontend/checker modules and their inert host-data vocabulary.
;; These are compile-time/checker permissions, never object computation.
(provide static-helper-rules)
(define static-helper-rules
  '((static-data
     "lang/static-data.rkt"
     ((require racket/list))
     (provide analysis-request-key
              analysis-result-key
              analysis-request
              (struct-out source-location)
              (struct-out source-node)
              (struct-out source-binding)
              (struct-out source-view)
              validate-source-view)
     (=
      Char
      Rat
      String
      analysis-request
      analysis-request-key
      analysis-result-key
      and
      andmap
      append
      application
      attalambda-static-request
      attalambda-static-result
      attalambda-static-v1
      binder
      binder-ids
      binding
      bindings
      boolean?
      bound
      builtin
      caddr
      cadr
      car
      case
      check
      child
      children
      column
      cond
      condition
      cons
      data
      define
      dependencies
      else
      entry
      eq?
      equal?
      error
      exact-nonnegative-integer?
      expected
      expected-forms
      expression
      expressions
      for
      forms
      global-ids
      group
      hash-count
      hash-has-key?
      hash-ref
      hash-set!
      id
      in-list
      kind
      lambda
      length
      let
      line
      list
      list?
      literal
      location
      location?
      make-hasheq
      make-hasheqv
      map
      member
      memq
      memv
      n
      name
      node
      not
      null?
      or
      position
      provide
      quote
      racket/list
      reason
      recursive?
      reference
      registered
      registry
      remove-duplicates
      require
      seen
      source
      source-binding
      source-binding-dependencies
      source-binding-id
      source-binding-location
      source-binding-name
      source-binding-recursive?
      source-binding-value
      source-binding?
      source-location
      source-location-column
      source-location-line
      source-location-position
      source-location-source
      source-location-span
      source-location?
      source-node
      source-node-children
      source-node-data
      source-node-id
      source-node-kind
      source-node-location
      source-node?
      source-view
      source-view-bindings
      source-view-expressions
      source-view-forms
      source-view-registry
      source-view?
      span
      static-source
      string?
      struct
      struct-out
      symbol?
      unless
      validate-source-view
      value
      view
      visited
      walk
      when))
    (static-source
     "lang/static-source.rkt"
     ((require racket/list "static-data.rkt"))
     (provide make-source-view)
     (=
      Char
      Rat
      String
      abstraction
      add1
      and
      append
      application
      applications
      argument
      arguments
      assq
      begin0
      binders
      binding
      body
      bound-name
      builtin
      builtins
      cadddr
      caddr
      cadr
      car
      cdr
      char?
      children
      clause
      clauses
      cond
      cons
      data
      datum
      define
      definition
      definition-parts
      definitions
      dependencies
      edges
      element
      elements
      else
      entry
      environment
      eq?
      error
      exact?
      expression
      findf
      foldr
      for
      for/fold
      form
      forms
      found
      free-identifier=?
      fresh-binding
      function
      globals
      group
      head
      id
      identifier?
      if
      in-list
      in-naturals
      index
      kind
      lambda
      length
      let
      let*
      list
      list-ref
      literal
      local
      location
      lower-let
      make-source-view
      map
      memq
      name
      names
      next-binding
      next-expression
      nil
      node
      not
      null?
      origin
      pair?
      parts
      path->string
      path?
      pieces
      provide
      quote
      racket/list
      rational?
      rec
      recursive?
      reference
      register
      registry
      remaining
      remove-duplicates
      require
      result-bindings
      result-expressions
      result-forms
      reverse
      set!
      source
      source-binding
      source-location
      source-node
      source-node-id
      source-view
      special?
      static-source
      string->symbol
      string?
      stx
      sub1
      sugar-expression
      symbol->string
      symbol?
      syntax->list
      syntax-bindings
      syntax-column
      syntax-e
      syntax-line
      syntax-position
      syntax-source
      syntax-span
      tail
      translate
      unary-let
      unless
      value))
    (static-types
     "runner/static/types.rkt"
     ((require racket/list))
     (provide (struct-out type-variable)
              (struct-out type-form)
              (struct-out scheme)
              monotype?
              base-type
              arrow-type
              list-type
              option-type
              result-type
              map-type)
     (=
      Arrow
      Bool
      Byte
      Char
      Error
      List
      Map
      Option
      Rat
      Result
      String
      Unit
      and
      andmap
      arguments
      arities
      arrow-type
      assq
      base-type
      cdr
      codomain
      define
      domain
      element
      entry
      exact-nonnegative-integer?
      id
      key
      lambda
      length
      list
      list-type
      list?
      map-type
      monotype?
      name
      option-type
      or
      provide
      quote
      racket/list
      raise-argument-error
      raise-arguments-error
      remove-duplicates
      require
      restricted
      result-type
      scheme
      struct
      struct-out
      type
      type-form
      type-form?
      type-variable
      type-variable?
      unless
      value
      values
      variables
      who))
    (static-proof
     "runner/static/proof.rkt"
     ((require racket/list))
     (provide (struct-out problem)
              (struct-out proof)
              established-proof
              proof-status
              proof-join)
     (RECURSIVE_TYPE_REQUIRED
      TYPE_CONFLICT
      UNREPRESENTED_ERROR_ALTERNATIVE
      UNSUPPORTED_CONTRACT
      UNSUPPORTED_DATA_DOMAIN
      actual
      and
      andmap
      append-map
      code
      cond
      conflict
      define
      dependencies
      detail
      else
      eq?
      established
      established-proof
      exact-nonnegative-integer?
      expected
      item
      lambda
      list?
      location
      memq
      null?
      ormap
      owner
      problem
      problem-code
      problem-codes
      problem?
      problems
      proof
      proof-dependencies
      proof-join
      proof-problems
      proof-status
      provide
      quote
      racket/list
      raise-arguments-error
      remove-duplicates
      require
      state
      states
      string?
      struct
      struct-out
      unless
      unproved
      values
      who))
    (static-substitution
     "runner/static/substitution.rkt"
     ((require racket/list "types.rkt"))
     (provide (struct-out solution)
              empty-solution
              make-fresh
              type-variables
              scheme-variables-free
              substitute-type
              substitute-scheme
              compose-substitutions
              apply-type
              apply-scheme
              instantiate
              generalize)
     (add1
      and
      andmap
      append
      append-map
      apply-scheme
      apply-type
      begin0
      bindings
      compose-substitutions
      cond
      current
      define
      else
      empty-solution
      entry
      environment
      environment-free
      exact-nonnegative-integer?
      excluded
      filter
      for/fold
      for/hasheqv
      free
      free-bindings
      fresh
      generalize
      hash-keys
      hash-ref
      hash-remove
      hash-set
      hash-values
      hash?
      hasheqv
      id
      ids
      immutable?
      in-hash
      in-list
      instantiate
      lambda
      list
      list?
      make-fresh
      map
      member
      memv
      monotype?
      new
      next
      not
      old
      ormap
      provide
      quote
      racket/list
      raise-argument-error
      raise-arguments-error
      remove-duplicates
      rename
      replacements
      require
      restricted
      result
      scheme
      scheme-restricted
      scheme-type
      scheme-variables
      scheme-variables-free
      set!
      solution
      solution-bindings
      solution-restricted
      solved
      start
      state
      struct
      struct-out
      substitute-scheme
      substitute-type
      substituted-restrictions
      type
      type-form
      type-form-arguments
      type-form-name
      type-form?
      type-variable
      type-variable-id
      type-variable?
      type-variables
      unless
      value
      values
      walk
      who
      without))
    (static-unification
     "runner/static/unification.rkt"
     ((require racket/list "types.rkt" "substitution.rkt"))
     (provide (struct-out equation-problem)
              (struct-out unsatisfied)
              unify
              restrict-data)
     (Bool
      Byte
      Char
      List
      Map
      Option
      RECURSIVE_TYPE_REQUIRED
      Rat
      Result
      String
      TYPE_CONFLICT
      UNSUPPORTED_DATA_DOMAIN
      Unit
      actual
      and
      append
      apply-type
      bind
      candidate
      check
      check-many
      code
      compose-substitutions
      cond
      cons
      container-domains
      current
      define
      define-values
      domain
      domains
      else
      empty-solution
      eq?
      equal?
      equate
      equation-problem
      expected
      failure
      for/fold
      hasheqv
      id
      if
      in-list
      initial
      left
      let
      list
      memq
      memv
      monotype?
      not
      null?
      problems
      provide
      quote
      racket/list
      raise-arguments-error
      range
      remove-duplicates
      require
      restrict-data
      result
      right
      solution
      solution-bindings
      solution-restricted
      solution?
      solved
      state
      struct
      struct-out
      type
      type-form-arguments
      type-form-name
      type-variable-id
      type-variable?
      type-variables
      types
      unify
      unless
      unsatisfied
      unsatisfied-problems
      unsatisfied?
      values
      variable))
    (static-type-display
     "runner/static/type-display.rkt"
     ((require racket/list racket/string "types.rkt" "substitution.rkt"))
     (provide type->string types->strings scheme->string)
     (+
      <
      Arrow
      and
      append
      append-map
      arg
      arguments
      arrow?
      cadr
      car
      codomain
      cond
      define
      display-type
      domain
      else
      eq?
      for/hasheqv
      hash-ref
      id
      if
      in-list
      in-naturals
      index
      input
      integer->char
      lambda
      map
      memv
      modulo
      names
      names-for
      null?
      number->string
      provide
      quote
      quotient
      racket/list
      racket/string
      remove-duplicates
      require
      scheme->string
      scheme-restricted
      scheme-type
      scheme-variables
      string
      string-append
      string-join
      symbol->string
      type
      type->string
      type-form-arguments
      type-form-name
      type-form?
      type-variable-id
      type-variable?
      type-variables
      types
      types->strings
      value
      values
      variable-name
      variables))
    (static-contracts
     "runner/static/contracts.rkt"
     ((require racket/list "types.rkt"))
     (provide (struct-out library-contract)
              catalog
              contract-ref
              validate-catalog)
     (=
      Bool
      Byte
      Char
      EMPTY-STRING
      Error
      FALSE
      NIL
      NONE
      Rat
      String
      TRUE
      UNIT
      UNREPRESENTED_ERROR_ALTERNATIVE
      UNSUPPORTED_CONTRACT
      Unit
      a
      abs
      add
      and
      andmap
      append
      arity
      arrow-type
      b
      base-type
      bool
      byte
      caddr
      cadr
      car
      catalog
      char
      complete
      cond
      contract-ref
      define
      div
      else
      entries
      entry
      eq
      eq?
      error
      error-to-string
      error-type
      exact-nonnegative-integer?
      exp
      findf
      floor
      foldr
      for
      for/list
      found
      gap-code
      gt
      gte
      id
      if
      implementations
      in-list
      is-nonnegative-whole
      is-ok
      is-whole
      is-zero
      lambda
      length
      library-contract
      library-contract-arity
      library-contract-gap-code
      library-contract-id
      library-contract-implementations
      library-contract-reason
      library-contract-signature
      library-contract-status
      library-contract-tests
      library-contract?
      list
      list-type
      list?
      lt
      lte
      map
      map-type
      memq
      mult
      neg
      not
      option-type
      or
      pair?
      parameters
      partial
      pending
      provide
      quote
      racket/list
      rat
      raw-comparison-boolean
      raw-make-checked-byte
      raw-make-checked-char-rat
      raw-make-rat
      raw-rat-div
      raw-render-map
      raw-result-unwrap-err
      raw-result-unwrap-ok
      raw-value-to-chars
      raw-zip-step
      reason
      recip
      remove-duplicates
      require
      restricted
      result
      result-type
      row
      scheme
      scheme?
      signature
      static-contracts
      status
      string
      string->symbol
      string-append
      string?
      struct
      struct-out
      sub
      succ
      symbol?
      tests
      type-variable
      typed-all?
      typed-and
      typed-any?
      typed-append
      typed-bool-to-string
      typed-byte-equal
      typed-byte-greater
      typed-byte-greater-equal
      typed-byte-less
      typed-byte-less-equal
      typed-byte-to-string
      typed-byte-value
      typed-bytes-to-string
      typed-char-equal
      typed-char-greater
      typed-char-greater-equal
      typed-char-less
      typed-char-less-equal
      typed-char-to-string
      typed-concat
      typed-cons
      typed-contains?
      typed-drop-rat
      typed-drop-while
      typed-error-to-string
      typed-filter
      typed-find
      typed-find-index
      typed-flatten
      typed-head
      typed-if
      typed-is-nil
      typed-len-rat
      typed-list-to-string
      typed-make-byte
      typed-make-char-rat
      typed-make-err
      typed-make-map
      typed-make-ok
      typed-make-some
      typed-make-string
      typed-map
      typed-map-contains?
      typed-map-empty?
      typed-map-lookup
      typed-map-remove
      typed-map-set
      typed-map-size
      typed-map-to-string
      typed-not
      typed-nth-rat
      typed-option-case
      typed-option-is-none
      typed-option-is-some
      typed-option-to-string
      typed-or
      typed-range-rat
      typed-rat-abs
      typed-rat-add
      typed-rat-div
      typed-rat-equal
      typed-rat-exp
      typed-rat-floor
      typed-rat-greater
      typed-rat-greater-equal
      typed-rat-is-nonnegative-whole
      typed-rat-is-whole
      typed-rat-is-zero
      typed-rat-less
      typed-rat-less-equal
      typed-rat-mult
      typed-rat-negate
      typed-rat-recip
      typed-rat-sub
      typed-rat-succ
      typed-rat-to-string
      typed-reduce
      typed-repeat-rat
      typed-result-is-err
      typed-result-is-ok
      typed-result-to-string
      typed-result-unwrap-err
      typed-result-unwrap-ok
      typed-reverse
      typed-string-append
      typed-string-contains?
      typed-string-empty?
      typed-string-equal
      typed-string-head
      typed-string-length-rat
      typed-string-prefix?
      typed-string-tail
      typed-string-to-bytes
      typed-string-to-string
      typed-tail
      typed-take-rat
      typed-take-while
      typed-unit-to-string
      typed-xor
      typed-zip
      unit
      unless
      unwrap-ok
      validate-catalog
      value-to-string
      variables
      when
      xor))
    (static-inference
     "runner/static/inference.rkt"
     ((require racket/list
               "../../lang/static-data.rkt"
               "types.rkt"
               "proof.rkt"
               "substitution.rkt"
               "unification.rkt"
               "contracts.rkt"))
     (provide (struct-out judgment)
              (struct-out call-inputs)
              (struct-out binding-contract)
              infer-expression
              bind-judgment)
     (>
      Arrow
      actual
      add1
      and
      application
      apply-type
      argument
      argument-type
      arrow-count
      arrow-type
      arrow?
      base-type
      bind-judgment
      binding
      binding-contract
      binding-contract-inputs
      binding-contract-proof
      binding-contract-signature
      body
      builtin
      cadr
      call-detail
      call-inputs
      call-inputs-name
      call-inputs-position
      call-inputs-remaining
      call-inputs-type
      car
      case
      check-equation
      children
      codomain
      complete
      complete?
      cond
      contract-ref
      current-inputs
      data
      define
      define-values
      detail
      domain
      else
      empty-solution
      entry
      environment
      eq?
      equation-problem-actual
      equation-problem-code
      equation-problem-expected
      error
      established
      established-proof
      established?
      expected
      filter
      finish
      for/hasheqv
      format
      freeze
      fresh
      function
      function-type
      generalize
      group
      hash-has-key?
      hash-ref
      hash-set
      hash-values
      hasheqv
      id
      if
      in-hash
      infer-expression
      inherited
      initial
      initializer
      input-template
      input-template-name
      input-template-position
      input-template-remaining
      input-template-signature
      input-template?
      inputs
      instantiate
      instantiate-here
      item
      judgment
      judgment-inputs
      judgment-proof
      judgment-type
      kind
      lambda
      let
      library-contract-arity
      library-contract-gap-code
      library-contract-reason
      library-contract-signature
      library-contract-status
      list
      literal
      local
      make-fresh
      map
      monotype?
      name
      next
      node
      nodes
      not
      obligation
      operand
      operator
      or
      output
      owner
      parameter
      position
      positive?
      problem
      proof
      proof-join
      proof-status
      provide
      quote
      racket/list
      reference
      remaining
      require
      residual
      result
      root
      scheme
      scheme-type
      set!
      shape
      signature
      signatures
      solution?
      solved
      source-node-children
      source-node-data
      source-node-id
      source-node-kind
      source-node-location
      state
      static-inference
      struct
      struct-copy
      struct-out
      sub1
      type
      type-form-arguments
      type-form-name
      type-form?
      type-variable?
      unify
      unsatisfied-problems
      values
      walk
      when))
    (static-analysis
     "runner/static/analysis.rkt"
     ((require racket/list
               "../../lang/static-data.rkt"
               "inference.rkt"
               "proof.rkt"
               "types.rkt"
               "substitution.rkt"
               "unification.rkt"
               "contracts.rkt"))
     (provide (struct-out definition-result)
              (struct-out analysis)
              analyze-view
              analysis-proof)
     (<
      =
      actual
      analysis
      analysis-definitions
      analysis-expressions
      analysis-proof
      analyze-view
      and
      append
      append-map
      apply
      apply-type
      assumption
      bind-judgment
      binding
      binding-contract
      binding-contract-signature
      bindings
      body
      call-inputs
      call-inputs-type
      car
      catalog
      children
      classified
      collect
      complete?
      cons
      consistency
      context
      define
      define-values
      definition-result
      definition-result-proof
      definitions
      dependency
      depends?
      entry
      environment
      eq?
      equal?
      equation-problem-actual
      equation-problem-code
      equation-problem-expected
      error
      established
      established-proof
      expressions
      filter
      final-nodes
      final-proof
      final-state
      for
      for/hasheqv
      for/list
      fresh
      global-references
      hash-has-key?
      hash-keys
      hash-ref
      hash-set
      hasheqv
      id
      if
      in-hash
      in-list
      infer-binding
      infer-expression
      inputs
      invalidate-self
      item
      judgment
      judgment-inputs
      judgment-proof
      judgment-type
      key
      lambda
      length
      list
      make-fresh
      map
      memv
      new
      node
      nodes
      normalize
      not
      or
      ormap
      problem
      proof
      proof-join
      proof-status
      provide
      quote
      racket/list
      recursive?
      reference
      remove-duplicates
      require
      result
      results
      scheme
      set!
      signature
      solution?
      sort
      source
      source-binding-dependencies
      source-binding-id
      source-binding-location
      source-binding-name
      source-binding-recursive?
      source-binding-value
      source-node-children
      source-node-data
      source-node-id
      source-node-kind
      source-view-bindings
      source-view-expressions
      source-view-forms
      source-view-registry
      sources
      state
      static-analysis
      struct
      struct-copy
      struct-out
      type
      unify
      unless
      unsatisfied-problems
      unsatisfied?
      validate-catalog
      validate-source-view
      values
      view
      visit
      visiting
      when))
    (static-coverage
     "runner/static/coverage.rkt"
     ((require racket/list
               "../../lang/static-data.rkt"
               "analysis.rkt"
               "inference.rkt"
               "proof.rkt"
               "types.rkt"
               "contracts.rkt"))
     (provide (struct-out check-summary)
              summarize-analysis
              coverage-percentage)
     (*
      +
      <
      <=
      =
      TYPE_CONFLICT
      all-proof
      analysis
      analysis-definitions
      analysis-expressions
      analysis-nodes
      analysis-view
      analysis?
      and
      andmap
      append
      apply
      by-id
      car
      catalog
      check
      check-summary
      checked
      children
      children-complete?
      complete?
      cond
      condition
      cons
      count
      coverage-percentage
      dc
      define
      definition-result-binding
      definition-result-proof
      definition-result-signature
      definition-result?
      definitions
      definitions-checked
      definitions-total
      dependencies
      ec
      else
      eq?
      equal?
      error
      established
      established?
      exact-nonnegative-integer?
      explain
      expressions
      expressions-checked
      expressions-total
      fail
      for
      for/hasheqv
      format
      full
      hash-has-key?
      hash-keys
      hash-ref
      hash-remove!
      hash-set!
      hash?
      id
      ids
      if
      in-hash
      in-list
      issue
      item
      judgment-proof
      judgment-type
      judgment?
      lambda
      length
      let
      list
      list?
      make-hasheqv
      map
      monotype?
      node
      nodes
      not
      or
      ormap
      pair?
      partial
      path
      paths
      problem-actual
      problem-code
      problem-expected
      problem-location
      problem-owner
      problems
      proof-dependencies
      proof-join
      proof-problems
      proof-status
      proof?
      provide
      quote
      quotient
      racket/list
      reason
      reference
      remainder
      remove-duplicates
      require
      result
      scheme?
      sort
      source-binding-id
      source-binding-value
      source-location-position
      source-location?
      source-node-children
      source-node-data
      source-node-id
      source-node-kind
      source-view-bindings
      source-view-expressions
      source-view-forms
      source-view-registry
      source-view?
      state
      static-coverage
      struct
      struct-out
      summarize-analysis
      tails
      tenths
      total
      unless
      validate-catalog
      validate-judgment
      validate-proof
      validate-source-view
      values
      verdict
      view
      visiting
      walk
      when
      zero?))
    (static-report
     "runner/static/report.rkt"
     ((require racket/list
               racket/string
               "../../lang/static-data.rkt"
               "analysis.rkt"
               "coverage.rkt"
               "inference.rkt"
               "proof.rkt"
               "type-display.rkt"))
     (provide render-report)
     (+
      <
      <=
      RECURSIVE_TYPE_REQUIRED
      TYPE_CONFLICT
      UNSUPPORTED_DATA_DOMAIN
      analysis-definitions
      analysis-expressions
      analysis-view
      and
      apply
      argmin
      binding-name
      by-id
      caddr
      cadr
      candidates
      car
      case
      cc
      cf
      char->integer
      char-general-category
      character
      check-summary-analysis
      check-summary-definitions-checked
      check-summary-definitions-total
      check-summary-expressions-checked
      check-summary-expressions-total
      check-summary-paths
      check-summary-problems
      check-summary-verdict
      checked
      count
      count-line
      coverage-percentage
      define
      definition-result-binding
      definition-result-proof
      definition-result-signature
      definitions
      diagnostic
      else
      enclosing-lambda
      entry
      eq?
      error
      established
      explanation
      fail
      filter
      for/hasheqv
      for/list
      format
      full
      hash-ref
      id
      if
      in-list
      in-string
      incomplete
      inferred
      issue
      item
      judgment-proof
      label
      lambda
      lambdas
      last
      list
      location
      location-text
      map
      memq
      name
      name-text
      nested
      node
      not
      null?
      number->string
      or
      origin
      pair?
      partial
      path
      path-text
      position
      prefix
      primary
      problem-actual
      problem-code
      problem-detail
      problem-expected
      problem-location
      problem-owner
      problem-text
      problems
      proof-dependencies
      proof-problems
      proof-status
      provide
      quote
      racket/list
      racket/string
      render-report
      require
      result
      safe
      scheme->string
      sort
      source-binding-id
      source-binding-name
      source-location-column
      source-location-line
      source-location-position
      source-location-source
      source-location-span
      source-name
      source-node-location
      source-view-expressions
      source-view-registry
      span
      start
      static-report
      string
      string-append
      string-join
      summary
      text
      top-level-dependencies
      total
      types
      types->strings
      values
      view
      zero?
      zl
      zp))
    (static-command
     "runner/static/command.rkt"
     ((require "../source-file.rkt"
               "../diagnostics.rkt"
               "frontend.rkt"
               "analysis.rkt"
               "coverage.rkt"
               "report.rkt"))
     (provide run-check current-check-prepare current-check-analyze)
     (analyze-view
      break-enabled
      case
      check-summary-verdict
      cond
      current-check-analyze
      current-check-prepare
      current-custodian
      current-error-port
      current-output-port
      custodian-shutdown-all
      define
      diagnose
      display
      dynamic-wind
      else
      eq?
      error
      exn:break?
      fail
      failure
      flush-output
      format-source-problem
      full
      if
      inspect-source-file
      internal
      interrupted
      invalid
      issue
      lambda
      make-custodian
      make-parameter
      owner
      parameterize
      partial
      prepare-source
      provide
      quote
      render-report
      report
      require
      run-check
      source
      source-name
      source-problem
      source-problem-kind
      source-problem?
      static-command
      status
      summarize-analysis
      summary
      unless
      view
      void
      with-handlers))))
