#lang racket/base
;; Exact private frontend modules and their inert host-data vocabulary.
;; These are compile-time/frontend permissions, never object computation.
(provide static-helper-rules)
(define static-helper-rules
  '((static-data
     "lang/static-data.rkt"
     ((require racket/list))
     (provide analysis-request-key
              analysis-result-key
              analysis-request
              (struct-out source-location)
              (struct-out source-node)
              (struct-out source-binding)
              (struct-out source-view)
              validate-source-view)
     (=
      Char
      Rat
      String
      analysis-request
      analysis-request-key
      analysis-result-key
      and
      andmap
      append
      application
      attalambda-static-request
      attalambda-static-result
      attalambda-static-v1
      binder
      binder-ids
      binding
      bindings
      boolean?
      bound
      builtin
      caddr
      cadr
      car
      case
      check
      child
      children
      column
      cond
      condition
      cons
      data
      define
      dependencies
      else
      entry
      eq?
      equal?
      error
      exact-nonnegative-integer?
      expected
      expected-forms
      expression
      expressions
      for
      forms
      global-ids
      group
      hash-count
      hash-has-key?
      hash-ref
      hash-set!
      id
      in-list
      kind
      lambda
      length
      let
      line
      list
      list?
      literal
      location
      location?
      make-hasheq
      make-hasheqv
      map
      member
      memq
      memv
      n
      name
      node
      not
      null?
      or
      position
      provide
      quote
      racket/list
      reason
      recursive?
      reference
      registered
      registry
      remove-duplicates
      require
      seen
      source
      source-binding
      source-binding-dependencies
      source-binding-id
      source-binding-location
      source-binding-name
      source-binding-recursive?
      source-binding-value
      source-binding?
      source-location
      source-location-column
      source-location-line
      source-location-position
      source-location-source
      source-location-span
      source-location?
      source-node
      source-node-children
      source-node-data
      source-node-id
      source-node-kind
      source-node-location
      source-node?
      source-view
      source-view-bindings
      source-view-expressions
      source-view-forms
      source-view-registry
      source-view?
      span
      static-source
      string?
      struct
      struct-out
      symbol?
      unless
      validate-source-view
      value
      view
      visited
      walk
      when))
    (static-source
     "lang/static-source.rkt"
     ((require racket/list "static-data.rkt"))
     (provide make-source-view)
     (=
      Char
      Rat
      String
      abstraction
      add1
      and
      append
      application
      applications
      argument
      arguments
      assq
      begin0
      binders
      binding
      body
      bound-name
      builtin
      builtins
      cadddr
      caddr
      cadr
      car
      cdr
      char?
      children
      clause
      clauses
      cond
      cons
      data
      datum
      define
      definition
      definition-parts
      definitions
      dependencies
      edges
      element
      elements
      else
      entry
      environment
      eq?
      error
      exact?
      expression
      findf
      foldr
      for
      for/fold
      form
      forms
      found
      free-identifier=?
      fresh-binding
      function
      globals
      group
      head
      id
      identifier?
      if
      in-list
      in-naturals
      index
      kind
      lambda
      length
      let
      let*
      list
      list-ref
      literal
      local
      location
      lower-let
      make-source-view
      map
      memq
      name
      names
      next-binding
      next-expression
      nil
      node
      not
      null?
      origin
      pair?
      parts
      path->string
      path?
      pieces
      provide
      quote
      racket/list
      rational?
      rec
      recursive?
      reference
      register
      registry
      remaining
      remove-duplicates
      require
      result-bindings
      result-expressions
      result-forms
      reverse
      set!
      source
      source-binding
      source-location
      source-node
      source-node-id
      source-view
      special?
      static-source
      string->symbol
      string?
      stx
      sub1
      sugar-expression
      symbol->string
      symbol?
      syntax->list
      syntax-bindings
      syntax-column
      syntax-e
      syntax-line
      syntax-position
      syntax-source
      syntax-span
      tail
      translate
      unary-let
      unless
      value))))
